import mongoose from 'mongoose';
import Book from '../model/Book';
import Word from '../model/Word';
import User from '../model/User';
import { hashPassword } from '../utils/crypto';

const DB_URI = process.env.DB_URI || 'mongodb://localhost:27017/vocab_memory_system';

// 成都小学英语词库数据
const vocabularyData = {
  // 一年级上册 - 新启航
  '1-上': {
    name: '一年级上册',
    grade: 1,
    semester: '上',
    publisher: '新启航',
    words: [
      { en: 'hello', cn: '你好', phonetic: '/həˈləʊ/' },
      { en: 'hi', cn: '嗨', phonetic: '/haɪ/' },
      { en: 'goodbye', cn: '再见', phonetic: '/ɡʊdˈbaɪ/' },
      { en: 'bye', cn: '再见', phonetic: '/baɪ/' },
      { en: 'I', cn: '我', phonetic: '/aɪ/' },
      { en: 'am', cn: '是', phonetic: '/æm/' },
      { en: 'you', cn: '你', phonetic: '/juː/' },
      { en: 'are', cn: '是', phonetic: '/ɑː/' },
      { en: 'miss', cn: '小姐;老师', phonetic: '/mɪs/' },
      { en: 'mr', cn: '先生', phonetic: '/ˈmɪstə/' },
      { en: 'and', cn: '和', phonetic: '/ænd/' },
      { en: 'yes', cn: '是', phonetic: '/jes/' },
      { en: 'no', cn: '不', phonetic: '/nəʊ/' },
      { en: 'please', cn: '请', phonetic: '/pliːz/' },
      { en: 'thank', cn: '谢谢', phonetic: '/θæŋk/' },
      { en: 'sorry', cn: '对不起', phonetic: '/ˈsɒri/' },
      { en: 'a', cn: '一个', phonetic: '/ə/' },
      { en: 'an', cn: '一个', phonetic: '/ən/' },
      { en: 'the', cn: '这；那', phonetic: '/ðə/' },
      { en: 'it', cn: '它', phonetic: '/ɪt/' },
      { en: 'is', cn: '是', phonetic: '/ɪz/' },
      { en: 'this', cn: '这', phonetic: '/ðɪs/' },
      { en: 'that', cn: '那', phonetic: '/ðæt/' },
      { en: 'what', cn: '什么', phonetic: '/wɒt/' },
      { en: 'my', cn: '我的', phonetic: '/maɪ/' },
      { en: 'your', cn: '你的', phonetic: '/jɔː/' },
      { en: 'name', cn: '名字', phonetic: '/neɪm/' },
      { en: 'cat', cn: '猫', phonetic: '/kæt/' },
      { en: 'dog', cn: '狗', phonetic: '/dɒɡ/' },
      { en: 'bird', cn: '鸟', phonetic: '/bɜːd/' },
      { en: 'fish', cn: '鱼', phonetic: '/fɪʃ/' },
      { en: 'apple', cn: '苹果', phonetic: '/ˈæpl/' },
      { en: 'banana', cn: '香蕉', phonetic: '/bəˈnɑːnə/' },
      { en: 'book', cn: '书', phonetic: '/bʊk/' },
      { en: 'pen', cn: '钢笔', phonetic: '/pen/' },
      { en: 'pencil', cn: '铅笔', phonetic: '/ˈpensl/' },
      { en: 'ruler', cn: '尺子', phonetic: '/ˈruːlə/' },
      { en: 'bag', cn: '包', phonetic: '/bæɡ/' },
      { en: 'one', cn: '一', phonetic: '/wʌn/' },
      { en: 'two', cn: '二', phonetic: '/tuː/' },
      { en: 'three', cn: '三', phonetic: '/θriː/' },
      { en: 'four', cn: '四', phonetic: '/fɔː/' },
      { en: 'five', cn: '五', phonetic: '/faɪv/' },
      { en: 'six', cn: '六', phonetic: '/sɪks/' },
      { en: 'seven', cn: '七', phonetic: '/ˈsevn/' },
      { en: 'eight', cn: '八', phonetic: '/eɪt/' },
      { en: 'nine', cn: '九', phonetic: '/naɪn/' },
      { en: 'ten', cn: '十', phonetic: '/ten/' },
    ]
  },
  // 一年级下册 - 新启航
  '1-下': {
    name: '一年级下册',
    grade: 1,
    semester: '下',
    publisher: '新启航',
    words: [
      { en: 'red', cn: '红色', phonetic: '/red/' },
      { en: 'blue', cn: '蓝色', phonetic: '/bluː/' },
      { en: 'yellow', cn: '黄色', phonetic: '/ˈjeləʊ/' },
      { en: 'green', cn: '绿色', phonetic: '/ɡriːn/' },
      { en: 'orange', cn: '橙色', phonetic: '/ˈɒrɪndʒ/' },
      { en: 'purple', cn: '紫色', phonetic: '/ˈpɜːpl/' },
      { en: 'pink', cn: '粉色', phonetic: '/pɪŋk/' },
      { en: 'black', cn: '黑色', phonetic: '/blæk/' },
      { en: 'white', cn: '白色', phonetic: '/waɪt/' },
      { en: 'brown', cn: '棕色', phonetic: '/braʊn/' },
      { en: 'big', cn: '大的', phonetic: '/bɪɡ/' },
      { en: 'small', cn: '小的', phonetic: '/smɔːl/' },
      { en: 'tall', cn: '高的', phonetic: '/tɔːl/' },
      { en: 'short', cn: '短的；矮的', phonetic: '/ʃɔːt/' },
      { en: 'long', cn: '长的', phonetic: '/lɒŋ/' },
      { en: 'new', cn: '新的', phonetic: '/njuː/' },
      { en: 'old', cn: '旧的', phonetic: '/əʊld/' },
      { en: 'happy', cn: '高兴的', phonetic: '/ˈhæpi/' },
      { en: 'sad', cn: '伤心的', phonetic: '/sæd/' },
      { en: 'boy', cn: '男孩', phonetic: '/bɔɪ/' },
      { en: 'girl', cn: '女孩', phonetic: '/ɡɜːl/' },
      { en: 'man', cn: '男人', phonetic: '/mæn/' },
      { en: 'woman', cn: '女人', phonetic: '/ˈwʊmən/' },
      { en: 'baby', cn: '婴儿', phonetic: '/ˈbeɪbi/' },
      { en: 'family', cn: '家庭', phonetic: '/ˈfæmɪli/' },
      { en: 'mother', cn: '母亲', phonetic: '/ˈmʌðə/' },
      { en: 'father', cn: '父亲', phonetic: '/ˈfɑːðə/' },
      { en: 'sister', cn: '姐妹', phonetic: '/ˈsɪstə/' },
      { en: 'brother', cn: '兄弟', phonetic: '/ˈbrʌðə/' },
      { en: 'grandma', cn: '奶奶；外婆', phonetic: '/ˈɡrænmɑː/' },
      { en: 'grandpa', cn: '爷爷；外公', phonetic: '/ˈɡrænpɑː/' },
      { en: 'friend', cn: '朋友', phonetic: '/frend/' },
      { en: 'teacher', cn: '老师', phonetic: '/ˈtiːtʃə/' },
      { en: 'student', cn: '学生', phonetic: '/ˈstjuːdnt/' },
      { en: 'school', cn: '学校', phonetic: '/skuːl/' },
      { en: 'classroom', cn: '教室', phonetic: '/ˈklɑːsruːm/' },
      { en: 'desk', cn: '书桌', phonetic: '/desk/' },
      { en: 'chair', cn: '椅子', phonetic: '/tʃeə/' },
      { en: 'door', cn: '门', phonetic: '/dɔː/' },
      { en: 'window', cn: '窗户', phonetic: '/ˈwɪndəʊ/' },
    ]
  },
  // 二年级上册 - 新启航
  '2-上': {
    name: '二年级上册',
    grade: 2,
    semester: '上',
    publisher: '新启航',
    words: [
      { en: 'morning', cn: '早晨', phonetic: '/ˈmɔːnɪŋ/' },
      { en: 'afternoon', cn: '下午', phonetic: '/ˌɑːftəˈnuːn/' },
      { en: 'evening', cn: '晚上', phonetic: '/ˈiːvnɪŋ/' },
      { en: 'night', cn: '夜晚', phonetic: '/naɪt/' },
      { en: 'day', cn: '天；日', phonetic: '/deɪ/' },
      { en: 'today', cn: '今天', phonetic: '/təˈdeɪ/' },
      { en: 'sun', cn: '太阳', phonetic: '/sʌn/' },
      { en: 'moon', cn: '月亮', phonetic: '/muːn/' },
      { en: 'star', cn: '星星', phonetic: '/stɑː/' },
      { en: 'sky', cn: '天空', phonetic: '/skaɪ/' },
      { en: 'cloud', cn: '云', phonetic: '/klaʊd/' },
      { en: 'rain', cn: '雨', phonetic: '/reɪn/' },
      { en: 'snow', cn: '雪', phonetic: '/snəʊ/' },
      { en: 'wind', cn: '风', phonetic: '/wɪnd/' },
      { en: 'flower', cn: '花', phonetic: '/ˈflaʊə/' },
      { en: 'tree', cn: '树', phonetic: '/triː/' },
      { en: 'grass', cn: '草', phonetic: '/ɡrɑːs/' },
      { en: 'water', cn: '水', phonetic: '/ˈwɔːtə/' },
      { en: 'food', cn: '食物', phonetic: '/fuːd/' },
      { en: 'fruit', cn: '水果', phonetic: '/fruːt/' },
      { en: 'rice', cn: '米饭', phonetic: '/raɪs/' },
      { en: 'bread', cn: '面包', phonetic: '/bred/' },
      { en: 'milk', cn: '牛奶', phonetic: '/mɪlk/' },
      { en: 'egg', cn: '鸡蛋', phonetic: '/eɡ/' },
      { en: 'cake', cn: '蛋糕', phonetic: '/keɪk/' },
      { en: 'candy', cn: '糖果', phonetic: '/ˈkændi/' },
      { en: 'ice cream', cn: '冰淇淋', phonetic: '/ˌaɪs ˈkriːm/' },
      { en: 'juice', cn: '果汁', phonetic: '/dʒuːs/' },
      { en: 'tea', cn: '茶', phonetic: '/tiː/' },
      { en: 'coffee', cn: '咖啡', phonetic: '/ˈkɒfi/' },
      { en: 'head', cn: '头', phonetic: '/hed/' },
      { en: 'face', cn: '脸', phonetic: '/feɪs/' },
      { en: 'eye', cn: '眼睛', phonetic: '/aɪ/' },
      { en: 'ear', cn: '耳朵', phonetic: '/ɪə/' },
      { en: 'nose', cn: '鼻子', phonetic: '/nəʊz/' },
      { en: 'mouth', cn: '嘴巴', phonetic: '/maʊθ/' },
      { en: 'hand', cn: '手', phonetic: '/hænd/' },
      { en: 'foot', cn: '脚', phonetic: '/fʊt/' },
      { en: 'arm', cn: '手臂', phonetic: '/ɑːm/' },
      { en: 'leg', cn: '腿', phonetic: '/leɡ/' },
    ]
  },
  // 二年级下册 - 新启航
  '2-下': {
    name: '二年级下册',
    grade: 2,
    semester: '下',
    publisher: '新启航',
    words: [
      { en: 'run', cn: '跑', phonetic: '/rʌn/' },
      { en: 'walk', cn: '走', phonetic: '/wɔːk/' },
      { en: 'jump', cn: '跳', phonetic: '/dʒʌmp/' },
      { en: 'swim', cn: '游泳', phonetic: '/swɪm/' },
      { en: 'fly', cn: '飞', phonetic: '/flaɪ/' },
      { en: 'sing', cn: '唱歌', phonetic: '/sɪŋ/' },
      { en: 'dance', cn: '跳舞', phonetic: '/dɑːns/' },
      { en: 'draw', cn: '画画', phonetic: '/drɔː/' },
      { en: 'read', cn: '读', phonetic: '/riːd/' },
      { en: 'write', cn: '写', phonetic: '/raɪt/' },
      { en: 'play', cn: '玩', phonetic: '/pleɪ/' },
      { en: 'eat', cn: '吃', phonetic: '/iːt/' },
      { en: 'drink', cn: '喝', phonetic: '/drɪŋk/' },
      { en: 'sleep', cn: '睡觉', phonetic: '/sliːp/' },
      { en: 'sit', cn: '坐', phonetic: '/sɪt/' },
      { en: 'stand', cn: '站', phonetic: '/stænd/' },
      { en: 'open', cn: '打开', phonetic: '/ˈəʊpən/' },
      { en: 'close', cn: '关闭', phonetic: '/kləʊz/' },
      { en: 'come', cn: '来', phonetic: '/kʌm/' },
      { en: 'go', cn: '去', phonetic: '/ɡəʊ/' },
      { en: 'like', cn: '喜欢', phonetic: '/laɪk/' },
      { en: 'love', cn: '爱', phonetic: '/lʌv/' },
      { en: 'have', cn: '有', phonetic: '/hæv/' },
      { en: 'want', cn: '想要', phonetic: '/wɒnt/' },
      { en: 'see', cn: '看见', phonetic: '/siː/' },
      { en: 'hear', cn: '听见', phonetic: '/hɪə/' },
      { en: 'speak', cn: '说', phonetic: '/spiːk/' },
      { en: 'listen', cn: '听', phonetic: '/ˈlɪsn/' },
      { en: 'look', cn: '看', phonetic: '/lʊk/' },
      { en: 'watch', cn: '观看', phonetic: '/wɒtʃ/' },
      { en: 'help', cn: '帮助', phonetic: '/help/' },
      { en: 'give', cn: '给', phonetic: '/ɡɪv/' },
      { en: 'get', cn: '得到', phonetic: '/ɡet/' },
      { en: 'make', cn: '制作', phonetic: '/meɪk/' },
      { en: 'do', cn: '做', phonetic: '/duː/' },
      { en: 'can', cn: '能；会', phonetic: '/kæn/' },
      { en: 'can\'t', cn: '不能；不会', phonetic: '/kɑːnt/' },
      { en: 'don\'t', cn: '不', phonetic: '/dəʊnt/' },
      { en: 'let\'s', cn: '让我们', phonetic: '/lets/' },
      { en: 'very', cn: '非常', phonetic: '/ˈveri/' },
    ]
  },
  // 三年级上册 - 外研社
  '3-上': {
    name: '三年级上册',
    grade: 3,
    semester: '上',
    publisher: '外研社',
    words: [
      { en: 'Ms', cn: '女士', phonetic: '/mɪz/' },
      { en: 'boy', cn: '男孩', phonetic: '/bɔɪ/' },
      { en: 'girl', cn: '女孩', phonetic: '/ɡɜːl/' },
      { en: 'whoops', cn: '哎哟', phonetic: '/wʊps/' },
      { en: 'and', cn: '那么；和', phonetic: '/ænd/' },
      { en: 'so', cn: '这么；那么', phonetic: '/səʊ/' },
      { en: 'how', cn: '怎样，如何', phonetic: '/haʊ/' },
      { en: 'how many', cn: '多少', phonetic: '/haʊ ˈmeni/' },
      { en: 'oh', cn: '哦', phonetic: '/əʊ/' },
      { en: 'no', cn: '不，不是', phonetic: '/nəʊ/' },
      { en: 'yes', cn: '是，对', phonetic: '/jes/' },
      { en: 'good', cn: '好的', phonetic: '/ɡʊd/' },
      { en: 'morning', cn: '早晨，上午', phonetic: '/ˈmɔːnɪŋ/' },
      { en: 'Good morning', cn: '早上好', phonetic: '/ɡʊd ˈmɔːnɪŋ/' },
      { en: 'afternoon', cn: '下午', phonetic: '/ˌɑːftəˈnuːn/' },
      { en: 'Good afternoon', cn: '下午好', phonetic: '/ɡʊd ˌɑːftəˈnuːn/' },
      { en: 'Mr', cn: '先生', phonetic: '/ˈmɪstə/' },
      { en: 'too', cn: '也', phonetic: '/tuː/' },
      { en: 'your', cn: '你的', phonetic: '/jɔː/' },
      { en: 'name', cn: '名字', phonetic: '/neɪm/' },
      { en: 'please', cn: '请', phonetic: '/pliːz/' },
      { en: 'point', cn: '指', phonetic: '/pɔɪnt/' },
      { en: 'to', cn: '向，朝……', phonetic: '/tuː/' },
      { en: 'the', cn: '这（那）个（些）', phonetic: '/ðə/' },
      { en: 'door', cn: '门', phonetic: '/dɔː/' },
      { en: 'window', cn: '窗', phonetic: '/ˈwɪndəʊ/' },
      { en: 'blackboard', cn: '黑板', phonetic: '/ˈblækbɔːd/' },
      { en: 'bird', cn: '鸟', phonetic: '/bɜːd/' },
      { en: 'desk', cn: '书桌，桌子', phonetic: '/desk/' },
      { en: 'chair', cn: '椅子', phonetic: '/tʃeə/' },
      { en: 'sit', cn: '坐', phonetic: '/sɪt/' },
      { en: 'down', cn: '向下', phonetic: '/daʊn/' },
      { en: 'Sit down', cn: '坐下', phonetic: '/sɪt daʊn/' },
      { en: 'stand', cn: '站', phonetic: '/stænd/' },
      { en: 'up', cn: '向上', phonetic: '/ʌp/' },
      { en: 'Stand up', cn: '站起来', phonetic: '/stænd ʌp/' },
      { en: 'open', cn: '打开', phonetic: '/ˈəʊpən/' },
      { en: 'book', cn: '书', phonetic: '/bʊk/' },
      { en: 'pencil', cn: '铅笔', phonetic: '/ˈpensl/' },
      { en: 'pen', cn: '钢笔', phonetic: '/pen/' },
      { en: 'bag', cn: '包，书包', phonetic: '/bæɡ/' },
      { en: 'pencil-box', cn: '铅笔盒', phonetic: '/ˈpensl bɒks/' },
      { en: 'ruler', cn: '尺子', phonetic: '/ˈruːlə/' },
      { en: 'eraser', cn: '橡皮', phonetic: '/ɪˈreɪzə/' },
      { en: 'crayon', cn: '蜡笔', phonetic: '/ˈkreɪən/' },
      { en: 'colours', cn: '颜色', phonetic: '/ˈkʌləz/' },
      { en: 'red', cn: '红色的', phonetic: '/red/' },
      { en: 'blue', cn: '蓝色的', phonetic: '/bluː/' },
      { en: 'yellow', cn: '黄色的', phonetic: '/ˈjeləʊ/' },
      { en: 'green', cn: '绿色的', phonetic: '/ɡriːn/' },
      { en: 'black', cn: '黑色的', phonetic: '/blæk/' },
      { en: 'orange', cn: '橙色的', phonetic: '/ˈɒrɪndʒ/' },
      { en: 'white', cn: '白色的', phonetic: '/waɪt/' },
      { en: 'brown', cn: '棕色的', phonetic: '/braʊn/' },
      { en: 'pink', cn: '粉色的', phonetic: '/pɪŋk/' },
      { en: 'it', cn: '它', phonetic: '/ɪt/' },
      { en: 'it\'s', cn: '它是', phonetic: '/ɪts/' },
      { en: 'is', cn: '是', phonetic: '/ɪz/' },
      { en: 'cap', cn: '帽子', phonetic: '/kæp/' },
      { en: 'cat', cn: '猫', phonetic: '/kæt/' },
      { en: 'dog', cn: '狗', phonetic: '/dɒɡ/' },
    ]
  },
  // 三年级下册 - 外研社
  '3-下': {
    name: '三年级下册',
    grade: 3,
    semester: '下',
    publisher: '外研社',
    words: [
      { en: 'song', cn: '歌曲', phonetic: '/sɒŋ/' },
      { en: 'favourite', cn: '最喜欢的', phonetic: '/ˈfeɪvərɪt/' },
      { en: 'colour', cn: '颜色', phonetic: '/ˈkʌlə/' },
      { en: 'here', cn: '这里', phonetic: '/hɪə/' },
      { en: 'here you are', cn: '给你', phonetic: '/hɪə juː ɑː/' },
      { en: 'sport', cn: '运动', phonetic: '/spɔːt/' },
      { en: 'football', cn: '足球', phonetic: '/ˈfʊtbɔːl/' },
      { en: 'basketball', cn: '篮球', phonetic: '/ˈbɑːskɪtbɔːl/' },
      { en: 'table tennis', cn: '乒乓球', phonetic: '/ˈteɪbl ˈtenɪs/' },
      { en: 'swimming', cn: '游泳', phonetic: '/ˈswɪmɪŋ/' },
      { en: 'morning exercises', cn: '早操', phonetic: '/ˈmɔːnɪŋ ˈeksəsaɪzɪz/' },
      { en: 'ride', cn: '骑', phonetic: '/raɪd/' },
      { en: 'bike', cn: '自行车', phonetic: '/baɪk/' },
      { en: 'ride my bike', cn: '骑自行车', phonetic: '/raɪd maɪ baɪk/' },
      { en: 'skip', cn: '跳绳', phonetic: '/skɪp/' },
      { en: 'fly', cn: '放（风筝）', phonetic: '/flaɪ/' },
      { en: 'kite', cn: '风筝', phonetic: '/kaɪt/' },
      { en: 'fly a kite', cn: '放风筝', phonetic: '/flaɪ ə kaɪt/' },
      { en: 'on', cn: '在……上面', phonetic: '/ɒn/' },
      { en: 'in', cn: '在……里面', phonetic: '/ɪn/' },
      { en: 'under', cn: '在……下面', phonetic: '/ˈʌndə/' },
      { en: 'behind', cn: '在……后面', phonetic: '/bɪˈhaɪnd/' },
      { en: 'bedroom', cn: '卧室', phonetic: '/ˈbedruːm/' },
      { en: 'living room', cn: '起居室，客厅', phonetic: '/ˈlɪvɪŋ ruːm/' },
      { en: 'kitchen', cn: '厨房', phonetic: '/ˈkɪtʃɪn/' },
      { en: 'toilet', cn: '厕所，卫生间', phonetic: '/ˈtɔɪlət/' },
      { en: 'home', cn: '家', phonetic: '/həʊm/' },
      { en: 'room', cn: '房间', phonetic: '/ruːm/' },
      { en: 'bed', cn: '床', phonetic: '/bed/' },
      { en: 'box', cn: '盒子', phonetic: '/bɒks/' },
      { en: 'toy', cn: '玩具', phonetic: '/tɔɪ/' },
      { en: 'behind', cn: '在……后面', phonetic: '/bɪˈhaɪnd/' },
      { en: 'park', cn: '公园', phonetic: '/pɑːk/' },
      { en: 'lake', cn: '湖', phonetic: '/leɪk/' },
      { en: 'tree', cn: '树', phonetic: '/triː/' },
      { en: 'flower', cn: '花', phonetic: '/ˈflaʊə/' },
      { en: 'photo', cn: '照片', phonetic: '/ˈfəʊtəʊ/' },
      { en: 'picture', cn: '图画，照片', phonetic: '/ˈpɪktʃə/' },
      { en: 'today', cn: '今天', phonetic: '/təˈdeɪ/' },
      { en: 'spring', cn: '春天', phonetic: '/sprɪŋ/' },
      { en: 'summer', cn: '夏天', phonetic: '/ˈsʌmə/' },
      { en: 'autumn', cn: '秋天', phonetic: '/ˈɔːtəm/' },
      { en: 'winter', cn: '冬天', phonetic: '/ˈwɪntə/' },
      { en: 'warm', cn: '温暖的', phonetic: '/wɔːm/' },
      { en: 'hot', cn: '热的', phonetic: '/hɒt/' },
      { en: 'cool', cn: '凉爽的', phonetic: '/kuːl/' },
      { en: 'cold', cn: '寒冷的', phonetic: '/kəʊld/' },
      { en: 'sunny', cn: '晴朗的', phonetic: '/ˈsʌni/' },
      { en: 'windy', cn: '有风的', phonetic: '/ˈwɪndi/' },
      { en: 'rain', cn: '雨；下雨', phonetic: '/reɪn/' },
      { en: 'snow', cn: '雪；下雪', phonetic: '/snəʊ/' },
    ]
  },
  // 四年级上册 - 外研社
  '4-上': {
    name: '四年级上册',
    grade: 4,
    semester: '上',
    publisher: '外研社',
    words: [
      { en: 'straight', cn: '直的；直线地', phonetic: '/streɪt/' },
      { en: 'go straight on', cn: '直着走', phonetic: '/ɡəʊ streɪt ɒn/' },
      { en: 'left', cn: '左边；向左', phonetic: '/left/' },
      { en: 'right', cn: '右边；向右', phonetic: '/raɪt/' },
      { en: 'live', cn: '居住', phonetic: '/lɪv/' },
      { en: 'street', cn: '街道', phonetic: '/striːt/' },
      { en: 'excuse me', cn: '对不起，打扰一下', phonetic: '/ɪkˈskjuːz miː/' },
      { en: 'turn left', cn: '向左转', phonetic: '/tɜːn left/' },
      { en: 'turn right', cn: '向右转', phonetic: '/tɜːn raɪt/' },
      { en: 'next to', cn: '在……旁边', phonetic: '/nekst tuː/' },
      { en: 'supermarket', cn: '超市', phonetic: '/ˈsuːpəmɑːkɪt/' },
      { en: 'cinema', cn: '电影院', phonetic: '/ˈsɪnəmɑː/' },
      { en: 'school', cn: '学校', phonetic: '/skuːl/' },
      { en: 'hospital', cn: '医院', phonetic: '/ˈhɒspɪtl/' },
      { en: 'station', cn: '车站', phonetic: '/ˈsteɪʃn/' },
      { en: 'train', cn: '火车', phonetic: '/treɪn/' },
      { en: 'hill', cn: '小山', phonetic: '/hɪl/' },
      { en: 'near', cn: '接近，靠近', phonetic: '/nɪə/' },
      { en: 'house', cn: '房子', phonetic: '/haʊs/' },
      { en: 'read', cn: '阅读', phonetic: '/riːd/' },
      { en: 'running', cn: '跑步', phonetic: '/ˈrʌnɪŋ/' },
      { en: 'picture', cn: '图片', phonetic: '/ˈpɪktʃə/' },
      { en: 'take', cn: '拍摄', phonetic: '/teɪk/' },
      { en: 'take pictures', cn: '拍照', phonetic: '/teɪk ˈpɪktʃəz/' },
      { en: 'children', cn: '孩子们', phonetic: '/ˈtʃɪldrən/' },
      { en: 'listen', cn: '听', phonetic: '/ˈlɪsn/' },
      { en: 'listen to', cn: '听……', phonetic: '/ˈlɪsn tuː/' },
      { en: 'talk', cn: '说话，交谈', phonetic: '/tɔːk/' },
      { en: 'talk to', cn: '和……交谈', phonetic: '/tɔːk tuː/' },
      { en: 'China', cn: '中国', phonetic: '/ˈtʃaɪnə/' },
      { en: 'Chinese', cn: '中国的，中国人的，汉语', phonetic: '/ˌtʃaɪˈniːz/' },
      { en: 'fast', cn: '快的', phonetic: '/fɑːst/' },
      { en: 'fast food', cn: '快餐', phonetic: '/fɑːst fuːd/' },
      { en: 'tomato', cn: '西红柿', phonetic: '/təˈmɑːtəʊ/' },
      { en: 'potato', cn: '土豆', phonetic: '/pəˈteɪtəʊ/' },
      { en: 'egg', cn: '鸡蛋', phonetic: '/eɡ/' },
      { en: 'noodles', cn: '面条', phonetic: '/ˈnuːdlz/' },
      { en: 'dumplings', cn: '饺子', phonetic: '/ˈdʌmplɪŋz/' },
      { en: 'rice', cn: '米饭', phonetic: '/raɪs/' },
      { en: 'fish', cn: '鱼；鱼肉', phonetic: '/fɪʃ/' },
      { en: 'meat', cn: '肉', phonetic: '/miːt/' },
      { en: 'milk', cn: '牛奶', phonetic: '/mɪlk/' },
      { en: 'juice', cn: '果汁', phonetic: '/dʒuːs/' },
      { en: 'can', cn: '可以，能', phonetic: '/kæn/' },
      { en: 'jump high', cn: '跳高', phonetic: '/dʒʌmp haɪ/' },
      { en: 'jump far', cn: '跳远', phonetic: '/dʒʌmp fɑː/' },
      { en: 'ride fast', cn: '骑得快', phonetic: '/raɪd fɑːst/' },
      { en: 'run fast', cn: '跑得快', phonetic: '/rʌn fɑːst/' },
    ]
  },
  // 四年级下册 - 外研社
  '4-下': {
    name: '四年级下册',
    grade: 4,
    semester: '下',
    publisher: '外研社',
    words: [
      { en: 'nice', cn: '友好的，亲切的', phonetic: '/naɪs/' },
      { en: 'clever', cn: '聪明的', phonetic: '/ˈklevə/' },
      { en: 'naughty', cn: '淘气的', phonetic: '/ˈnɔːti/' },
      { en: 'shy', cn: '害羞的', phonetic: '/ʃaɪ/' },
      { en: 'answer', cn: '回答', phonetic: '/ˈɑːnsə/' },
      { en: 'call', cn: '电话，呼叫', phonetic: '/kɔːl/' },
      { en: 'a bit', cn: '稍微，有点儿', phonetic: '/ə bɪt/' },
      { en: 'cool', cn: '酷的', phonetic: '/kuːl/' },
      { en: 'aunt', cn: '阿姨，姑妈', phonetic: '/ɑːnt/' },
      { en: 'uncle', cn: '叔叔，舅舅', phonetic: '/ˈʌŋkl/' },
      { en: 'big', cn: '年龄较大的', phonetic: '/bɪɡ/' },
      { en: 'little', cn: '年龄较小的', phonetic: '/ˈlɪtl/' },
      { en: 'cute', cn: '可爱的', phonetic: '/kjuːt/' },
      { en: 'city', cn: '城市', phonetic: '/ˈsɪti/' },
      { en: 'ship', cn: '船', phonetic: '/ʃɪp/' },
      { en: 'beautiful', cn: '美丽的', phonetic: '/ˈbjuːtɪfl/' },
      { en: 'whose', cn: '谁的', phonetic: '/huːz/' },
      { en: 'queen', cn: '女王', phonetic: '/kwiːn/' },
      { en: 'take', cn: '带去，拿走', phonetic: '/teɪk/' },
      { en: 'close', cn: '关，关闭', phonetic: '/kləʊz/' },
      { en: 'old', cn: '年老的', phonetic: '/əʊld/' },
      { en: 'young', cn: '年轻的', phonetic: '/jʌŋ/' },
      { en: 'were', cn: '是（are的过去式）', phonetic: '/wɜː/' },
      { en: 'was', cn: '是（is/am的过去式）', phonetic: '/wɒz/' },
      { en: 'then', cn: '当时，那时', phonetic: '/ðen/' },
      { en: 'grandparent', cn: '祖父/母', phonetic: '/ˈɡrænpeərənt/' },
      { en: 'were not', cn: '不是', phonetic: '/wɜː nɒt/' },
      { en: 'wasn\'t', cn: '不是', phonetic: '/ˈwɒznt/' },
      { en: 'hair', cn: '头发', phonetic: '/heə/' },
      { en: 'so', cn: '这么，那么', phonetic: '/səʊ/' },
      { en: 'short', cn: '短的', phonetic: '/ʃɔːt/' },
      { en: 'long', cn: '长的', phonetic: '/lɒŋ/' },
      { en: 'yesterday', cn: '昨天', phonetic: '/ˈjestədeɪ/' },
      { en: 'out', cn: '不在家，在外面', phonetic: '/aʊt/' },
      { en: 'well', cn: '健康的', phonetic: '/wel/' },
      { en: 'thanks', cn: '谢谢', phonetic: '/θæŋks/' },
      { en: 'sun', cn: '太阳', phonetic: '/sʌn/' },
      { en: 'lesson', cn: '一节课', phonetic: '/ˈlesn/' },
      { en: 'village', cn: '村庄，乡村', phonetic: '/ˈvɪlɪdʒ/' },
      { en: 'holiday', cn: '假期', phonetic: '/ˈhɒlədeɪ/' },
      { en: 'have a good time', cn: '玩得高兴', phonetic: '/hæv ə ɡʊd taɪm/' },
      { en: 'cloud', cn: '云', phonetic: '/klaʊd/' },
      { en: 'sunny', cn: '晴朗的', phonetic: '/ˈsʌni/' },
      { en: 'take', cn: '花费', phonetic: '/teɪk/' },
      { en: 'picnic', cn: '野餐', phonetic: '/ˈpɪknɪk/' },
      { en: 'great', cn: '太好了', phonetic: '/ɡreɪt/' },
      { en: 'because', cn: '因为', phonetic: '/bɪˈkɒz/' },
      { en: 'why', cn: '为什么', phonetic: '/waɪ/' },
    ]
  },
  // 五年级上册 - 人教版
  '5-上': {
    name: '五年级上册',
    grade: 5,
    semester: '上',
    publisher: '人教版',
    words: [
      { en: 'old', cn: '老的；年纪大的', phonetic: '/əʊld/' },
      { en: 'young', cn: '年轻的；岁数不大的', phonetic: '/jʌŋ/' },
      { en: 'funny', cn: '滑稽的；可笑的', phonetic: '/ˈfʌni/' },
      { en: 'kind', cn: '体贴的；慈祥的', phonetic: '/kaɪnd/' },
      { en: 'strict', cn: '要求严格的；严厉的', phonetic: '/strɪkt/' },
      { en: 'polite', cn: '有礼貌的；客气的', phonetic: '/pəˈlaɪt/' },
      { en: 'hard-working', cn: '工作努力的；辛勤的', phonetic: '/ˌhɑːd ˈwɜːkɪŋ/' },
      { en: 'helpful', cn: '有用的；愿意帮忙的', phonetic: '/ˈhelpfl/' },
      { en: 'clever', cn: '聪明的；聪颖的', phonetic: '/ˈklevə/' },
      { en: 'shy', cn: '羞怯的；腼腆的', phonetic: '/ʃaɪ/' },
      { en: 'know', cn: '知道；了解', phonetic: '/nəʊ/' },
      { en: 'our', cn: '我们的', phonetic: '/aʊə/' },
      { en: 'Ms', cn: '女士', phonetic: '/mɪz/' },
      { en: 'will', cn: '将要', phonetic: '/wɪl/' },
      { en: 'sometimes', cn: '有时；间或', phonetic: '/ˈsʌmtaɪmz/' },
      { en: 'robot', cn: '机器人', phonetic: '/ˈrəʊbɒt/' },
      { en: 'him', cn: '他', phonetic: '/hɪm/' },
      { en: 'speak', cn: '会说；会讲', phonetic: '/spiːk/' },
      { en: 'finish', cn: '完成；做好', phonetic: '/ˈfɪnɪʃ/' },
      { en: 'Monday', cn: '星期一', phonetic: '/ˈmʌndeɪ/' },
      { en: 'Tuesday', cn: '星期二', phonetic: '/ˈtjuːzdeɪ/' },
      { en: 'Wednesday', cn: '星期三', phonetic: '/ˈwenzdeɪ/' },
      { en: 'Thursday', cn: '星期四', phonetic: '/ˈθɜːzdeɪ/' },
      { en: 'Friday', cn: '星期五', phonetic: '/ˈfraɪdeɪ/' },
      { en: 'Saturday', cn: '星期六', phonetic: '/ˈsætədeɪ/' },
      { en: 'Sunday', cn: '星期日', phonetic: '/ˈsʌndeɪ/' },
      { en: 'weekend', cn: '周末', phonetic: '/ˌwiːkˈend/' },
      { en: 'wash', cn: '洗', phonetic: '/wɒʃ/' },
      { en: 'wash my clothes', cn: '洗我的衣服', phonetic: '/wɒʃ maɪ kləʊðz/' },
      { en: 'watch', cn: '看', phonetic: '/wɒtʃ/' },
      { en: 'watch TV', cn: '看电视', phonetic: '/wɒtʃ tiː viː/' },
      { en: 'do', cn: '做；干', phonetic: '/duː/' },
      { en: 'do homework', cn: '做作业', phonetic: '/duː ˈhəʊmwɜːk/' },
      { en: 'read', cn: '看；读', phonetic: '/riːd/' },
      { en: 'read books', cn: '看书', phonetic: '/riːd bʊks/' },
      { en: 'play', cn: '踢；玩；参加', phonetic: '/pleɪ/' },
      { en: 'play sports', cn: '做体育运动', phonetic: '/pleɪ spɔːts/' },
      { en: 'sandwich', cn: '三明治', phonetic: '/ˈsænwɪtʃ/' },
      { en: 'salad', cn: '蔬菜沙拉；混合沙拉', phonetic: '/ˈsæləd/' },
      { en: 'hamburger', cn: '汉堡包', phonetic: '/ˈhæmbɜːɡə/' },
      { en: 'ice cream', cn: '冰淇淋', phonetic: '/ˌaɪs ˈkriːm/' },
      { en: 'tea', cn: '茶；茶水', phonetic: '/tiː/' },
      { en: 'fresh', cn: '新鲜的', phonetic: '/freʃ/' },
      { en: 'healthy', cn: '健康的', phonetic: '/ˈhelθi/' },
      { en: 'delicious', cn: '美味的；可口的', phonetic: '/dɪˈlɪʃəs/' },
      { en: 'hot', cn: '辣的；辛辣的', phonetic: '/hɒt/' },
      { en: 'sweet', cn: '甜的', phonetic: '/swiːt/' },
      { en: 'drink', cn: '喝；饮', phonetic: '/drɪŋk/' },
      { en: 'thirsty', cn: '渴的；口渴的', phonetic: '/ˈθɜːsti/' },
    ]
  },
  // 五年级下册 - 人教版
  '5-下': {
    name: '五年级下册',
    grade: 5,
    semester: '下',
    publisher: '人教版',
    words: [
      { en: 'eat breakfast', cn: '吃早饭', phonetic: '/iːt ˈbrekfəst/' },
      { en: 'have...class', cn: '上……课', phonetic: '/hæv klɑːs/' },
      { en: 'play sports', cn: '进行体育运动', phonetic: '/pleɪ spɔːts/' },
      { en: 'exercise', cn: '活动；运动', phonetic: '/ˈeksəsaɪz/' },
      { en: 'do morning exercises', cn: '做早操', phonetic: '/duː ˈmɔːnɪŋ ˈeksəsaɪzɪz/' },
      { en: 'eat dinner', cn: '吃晚饭', phonetic: '/iːt ˈdɪnə/' },
      { en: 'clean my room', cn: '打扫我的房间', phonetic: '/kliːn maɪ ruːm/' },
      { en: 'go for a walk', cn: '散步', phonetic: '/ɡəʊ fɔːr ə wɔːk/' },
      { en: 'go shopping', cn: '买东西；购物', phonetic: '/ɡəʊ ˈʃɒpɪŋ/' },
      { en: 'take', cn: '学习；上', phonetic: '/teɪk/' },
      { en: 'dancing', cn: '跳舞；舞蹈', phonetic: '/ˈdɑːnsɪŋ/' },
      { en: 'take a dancing class', cn: '上舞蹈课', phonetic: '/teɪk ə ˈdɑːnsɪŋ klɑːs/' },
      { en: 'when', cn: '什么时候；何时', phonetic: '/wen/' },
      { en: 'after', cn: '在...后', phonetic: '/ˈɑːftə/' },
      { en: 'start', cn: '开始', phonetic: '/stɑːt/' },
      { en: 'usually', cn: '通常地；惯常地', phonetic: '/ˈjuːʒuəli/' },
      { en: 'Spain', cn: '西班牙', phonetic: '/speɪn/' },
      { en: 'late', cn: '晚；迟', phonetic: '/leɪt/' },
      { en: 'a.m.', cn: '午前；上午', phonetic: '/ˌeɪ ˈem/' },
      { en: 'p.m.', cn: '午后；下午', phonetic: '/ˌpiː ˈem/' },
      { en: 'why', cn: '为什么', phonetic: '/waɪ/' },
      { en: 'shop', cn: '去买东西；购物', phonetic: '/ʃɒp/' },
      { en: 'work', cn: '工作', phonetic: '/wɜːk/' },
      { en: 'last', cn: '上一个的；刚过去的', phonetic: '/lɑːst/' },
      { en: 'sounds', cn: '听起来好像', phonetic: '/saʊndz/' },
      { en: 'also', cn: '还；也', phonetic: '/ˈɔːlsəʊ/' },
      { en: 'busy', cn: '忙的', phonetic: '/ˈbɪzi/' },
      { en: 'need', cn: '需要', phonetic: '/niːd/' },
      { en: 'play', cn: '戏剧；剧本', phonetic: '/pleɪ/' },
      { en: 'letter', cn: '信', phonetic: '/ˈletə/' },
      { en: 'live', cn: '居住', phonetic: '/lɪv/' },
      { en: 'island', cn: '岛', phonetic: '/ˈaɪlənd/' },
      { en: 'always', cn: '总是；一直', phonetic: '/ˈɔːlweɪz/' },
      { en: 'cave', cn: '山洞；洞穴', phonetic: '/keɪv/' },
      { en: 'go swimming', cn: '去游泳', phonetic: '/ɡəʊ ˈswɪmɪŋ/' },
      { en: 'win', cn: '获胜', phonetic: '/wɪn/' },
      { en: 'spring', cn: '春天', phonetic: '/sprɪŋ/' },
      { en: 'summer', cn: '夏天', phonetic: '/ˈsʌmə/' },
      { en: 'autumn', cn: '秋天', phonetic: '/ˈɔːtəm/' },
      { en: 'winter', cn: '冬天', phonetic: '/ˈwɪntə/' },
      { en: 'season', cn: '季节', phonetic: '/ˈsiːzn/' },
      { en: 'picnic', cn: '野餐', phonetic: '/ˈpɪknɪk/' },
      { en: 'go on a picnic', cn: '去野餐', phonetic: '/ɡəʊ ɒn ə ˈpɪknɪk/' },
      { en: 'pick', cn: '摘；拾', phonetic: '/pɪk/' },
      { en: 'pick apples', cn: '摘苹果', phonetic: '/pɪk ˈæplz/' },
      { en: 'snowman', cn: '雪人', phonetic: '/ˈsnəʊmæn/' },
      { en: 'make a snowman', cn: '堆雪人', phonetic: '/meɪk ə ˈsnəʊmæn/' },
      { en: 'go swimming', cn: '去游泳', phonetic: '/ɡəʊ ˈswɪmɪŋ/' },
      { en: 'which', cn: '哪一个', phonetic: '/wɪtʃ/' },
      { en: 'best', cn: '最好地', phonetic: '/best/' },
    ]
  },
  // 六年级上册 - 人教版
  '6-上': {
    name: '六年级上册',
    grade: 6,
    semester: '上',
    publisher: '人教版',
    words: [
      { en: 'science', cn: '科学', phonetic: '/ˈsaɪəns/' },
      { en: 'museum', cn: '博物馆', phonetic: '/mjuˈziːəm/' },
      { en: 'post office', cn: '邮局', phonetic: '/pəʊst ˈɒfɪs/' },
      { en: 'bookstore', cn: '书店', phonetic: '/ˈbʊkstɔː/' },
      { en: 'cinema', cn: '电影院', phonetic: '/ˈsɪnəmɑː/' },
      { en: 'hospital', cn: '医院', phonetic: '/ˈhɒspɪtl/' },
      { en: 'crossing', cn: '十字路口', phonetic: '/ˈkrɒsɪŋ/' },
      { en: 'turn', cn: '转弯', phonetic: '/tɜːn/' },
      { en: 'straight', cn: '笔直地', phonetic: '/streɪt/' },
      { en: 'left', cn: '左边', phonetic: '/left/' },
      { en: 'right', cn: '右边', phonetic: '/raɪt/' },
      { en: 'ask', cn: '问', phonetic: '/ɑːsk/' },
      { en: 'sir', cn: '先生', phonetic: '/sɜː/' },
      { en: 'interesting', cn: '有趣的', phonetic: '/ˈɪntrəstɪŋ/' },
      { en: 'Italian', cn: '意大利的', phonetic: '/ɪˈtæliən/' },
      { en: 'restaurant', cn: '餐馆', phonetic: '/ˈrestrɒnt/' },
      { en: 'pizza', cn: '比萨饼', phonetic: '/ˈpiːtsə/' },
      { en: 'street', cn: '街道；马路', phonetic: '/striːt/' },
      { en: 'get', cn: '到达', phonetic: '/ɡet/' },
      { en: 'GPS', cn: '全球定位系统', phonetic: '/ˌdʒiː piː es/' },
      { en: 'feature', cn: '特点', phonetic: '/ˈfiːtʃə/' },
      { en: 'follow', cn: '跟着', phonetic: '/ˈfɒləʊ/' },
      { en: 'far', cn: '较远的', phonetic: '/fɑː/' },
      { en: 'tell', cn: '告诉', phonetic: '/tel/' },
      { en: 'on foot', cn: '步行', phonetic: '/ɒn fʊt/' },
      { en: 'by bus', cn: '乘公共汽车', phonetic: '/baɪ bʌs/' },
      { en: 'by plane', cn: '乘飞机', phonetic: '/baɪ pleɪn/' },
      { en: 'by taxi', cn: '乘出租车', phonetic: '/baɪ ˈtæksi/' },
      { en: 'by ship', cn: '乘轮船', phonetic: '/baɪ ʃɪp/' },
      { en: 'by subway', cn: '乘地铁', phonetic: '/baɪ ˈsʌbweɪ/' },
      { en: 'by train', cn: '乘火车', phonetic: '/baɪ treɪn/' },
      { en: 'slow down', cn: '慢下来', phonetic: '/sləʊ daʊn/' },
      { en: 'stop', cn: '停下', phonetic: '/stɒp/' },
      { en: 'traffic', cn: '交通', phonetic: '/ˈtræfɪk/' },
      { en: 'traffic lights', cn: '交通信号灯', phonetic: '/ˈtræfɪk laɪts/' },
      { en: 'wait', cn: '等待', phonetic: '/weɪt/' },
      { en: 'helmet', cn: '头盔', phonetic: '/ˈhelmɪt/' },
      { en: 'must', cn: '必须', phonetic: '/mʌst/' },
      { en: 'wear', cn: '戴', phonetic: '/weə/' },
      { en: 'attention', cn: '注意', phonetic: '/əˈtenʃn/' },
      { en: 'visit', cn: '参观；拜访', phonetic: '/ˈvɪzɪt/' },
      { en: 'film', cn: '电影', phonetic: '/fɪlm/' },
      { en: 'see a film', cn: '看电影', phonetic: '/siː ə fɪlm/' },
      { en: 'trip', cn: '旅行', phonetic: '/trɪp/' },
      { en: 'take a trip', cn: '去旅行', phonetic: '/teɪk ə trɪp/' },
      { en: 'supermarket', cn: '超市', phonetic: '/ˈsuːpəmɑːkɪt/' },
      { en: 'evening', cn: '晚上；傍晚', phonetic: '/ˈiːvnɪŋ/' },
      { en: 'tonight', cn: '今晚', phonetic: '/təˈnaɪt/' },
      { en: 'tomorrow', cn: '明天', phonetic: '/təˈmɒrəʊ/' },
      { en: 'dictionary', cn: '词典', phonetic: '/ˈdɪkʃənri/' },
    ]
  },
  // 六年级下册 - 人教版
  '6-下': {
    name: '六年级下册',
    grade: 6,
    semester: '下',
    publisher: '人教版',
    words: [
      { en: 'younger', cn: '更年轻的', phonetic: '/ˈjʌŋɡə/' },
      { en: 'older', cn: '更年长的', phonetic: '/ˈəʊldə/' },
      { en: 'taller', cn: '更高的', phonetic: '/ˈtɔːlə/' },
      { en: 'shorter', cn: '更矮的', phonetic: '/ˈʃɔːtə/' },
      { en: 'longer', cn: '更长的', phonetic: '/ˈlɒŋɡə/' },
      { en: 'thinner', cn: '更瘦的', phonetic: '/ˈθɪnə/' },
      { en: 'heavier', cn: '更重的', phonetic: '/ˈheviə/' },
      { en: 'bigger', cn: '更大的', phonetic: '/ˈbɪɡə/' },
      { en: 'smaller', cn: '更小的', phonetic: '/ˈsmɔːlə/' },
      { en: 'stronger', cn: '更强壮的', phonetic: '/ˈstrɒŋɡə/' },
      { en: 'dinosaur', cn: '恐龙', phonetic: '/ˈdaɪnəsɔː/' },
      { en: 'hall', cn: '大厅', phonetic: '/hɔːl/' },
      { en: 'metre', cn: '米', phonetic: '/ˈmiːtə/' },
      { en: 'than', cn: '比', phonetic: '/ðæn/' },
      { en: 'both', cn: '两个都', phonetic: '/bəʊθ/' },
      { en: 'kilogram', cn: '千克;公斤', phonetic: '/ˈkɪləɡræm/' },
      { en: 'countryside', cn: '乡村', phonetic: '/ˈkʌntrisaɪd/' },
      { en: 'lower', cn: '更低', phonetic: '/ˈləʊə/' },
      { en: 'shadow', cn: '阴影;影子', phonetic: '/ˈʃædəʊ/' },
      { en: 'smarter', cn: '更聪明的', phonetic: '/ˈsmɑːtə/' },
      { en: 'become', cn: '变成', phonetic: '/bɪˈkʌm/' },
      { en: 'cleaned', cn: '打扫', phonetic: '/kliːnd/' },
      { en: 'stayed', cn: '停留', phonetic: '/steɪd/' },
      { en: 'washed', cn: '洗', phonetic: '/wɒʃt/' },
      { en: 'watched', cn: '看', phonetic: '/wɒtʃt/' },
      { en: 'had', cn: '得病', phonetic: '/hæd/' },
      { en: 'had a cold', cn: '感冒', phonetic: '/hæd ə kəʊld/' },
      { en: 'slept', cn: '睡觉', phonetic: '/slept/' },
      { en: 'saw', cn: '看见', phonetic: '/sɔː/' },
      { en: 'read', cn: '读', phonetic: '/red/' },
      { en: 'last', cn: '上一个的', phonetic: '/lɑːst/' },
      { en: 'yesterday', cn: '昨天', phonetic: '/ˈjestədeɪ/' },
      { en: 'before', cn: '在...之前', phonetic: '/bɪˈfɔː/' },
      { en: 'drank', cn: '喝', phonetic: '/dræŋk/' },
      { en: 'show', cn: '演出', phonetic: '/ʃəʊ/' },
      { en: 'magazine', cn: '杂志', phonetic: '/ˌmæɡəˈziːn/' },
      { en: 'better', cn: '更好的', phonetic: '/ˈbetə/' },
      { en: 'faster', cn: '更快的', phonetic: '/ˈfɑːstə/' },
      { en: 'hotel', cn: '旅馆', phonetic: '/həʊˈtel/' },
      { en: 'fixed', cn: '修理', phonetic: '/fɪkst/' },
      { en: 'broken', cn: '破损的', phonetic: '/ˈbrəʊkən/' },
      { en: 'lamp', cn: '台灯', phonetic: '/læmp/' },
      { en: 'enjoy', cn: '享受...乐趣', phonetic: '/ɪnˈdʒɔɪ/' },
      { en: 'stay', cn: '暂住；逗留', phonetic: '/steɪ/' },
      { en: 'went', cn: '去', phonetic: '/went/' },
      { en: 'camp', cn: '野营', phonetic: '/kæmp/' },
      { en: 'went camping', cn: '去野营', phonetic: '/went ˈkæmpɪŋ/' },
      { en: 'fish', cn: '钓鱼', phonetic: '/fɪʃ/' },
      { en: 'went fishing', cn: '去钓鱼', phonetic: '/went ˈfɪʃɪŋ/' },
      { en: 'rode', cn: '骑', phonetic: '/rəʊd/' },
      { en: 'rode a bike', cn: '骑自行车', phonetic: '/rəʊd ə baɪk/' },
    ]
  }
};

// 初始化管理员账号
async function initAdmin() {
  const existAdmin = await User.findOne({ username: 'admin' });
  if (!existAdmin) {
    const hashedPassword = await hashPassword('Admin123!');
    const admin = new User({
      username: 'admin',
      password: hashedPassword,
      realName: '系统管理员',
      role: 'admin',
      status: 1,
    });
    await admin.save();
    console.log('✅ 初始管理员账号创建成功: admin / Admin123!');
  } else {
    console.log('ℹ️  管理员账号已存在');
  }
}

// 初始化词书和单词
async function initVocabulary() {
  // 检查是否已有词书
  const bookCount = await Book.countDocuments();
  if (bookCount > 0) {
    console.log(`ℹ️  词书已存在，共 ${bookCount} 本`);
    return;
  }

  console.log('📦 开始初始化成都小学英语词库...');

  for (const [key, bookData] of Object.entries(vocabularyData)) {
    // 创建词书
    const book = new Book({
      name: bookData.name,
      grade: bookData.grade,
      semester: bookData.semester,
      publisher: bookData.publisher,
      wordCount: bookData.words.length,
      status: 1,
    });
    await book.save();

    // 批量创建单词
    const words = bookData.words.map(word => ({
      en: word.en,
      cn: word.cn,
      phonetic: word.phonetic,
      grade: bookData.grade,
      bookId: book._id,
      bookName: book.name,
    }));
    await Word.insertMany(words);

    console.log(`  ✅ ${bookData.name} (${bookData.publisher}) - ${bookData.words.length} 个单词`);
  }

  console.log('🎉 词库初始化完成！');
}

// 主函数
async function main() {
  try {
    await mongoose.connect(DB_URI);
    console.log('📦 数据库连接成功');
    
    await initAdmin();
    await initVocabulary();
    
    await mongoose.disconnect();
    console.log('🎉 初始化完成');
    process.exit(0);
  } catch (error) {
    console.error('❌ 初始化失败:', error);
    process.exit(1);
  }
}

main();
